# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UHrBFdNqE_stb1xr8QPxQD2kO8EPHE65
"""

from suma import suma
from resta import resta
from multiplicacion import multiplicacion
from Division import division

def menu():
    while True:
        print("\n--- Bienvenido a la Calculadora del equipo 5 :)---")
        print("Por favor, selecciona una opción:")
        print("1.- Suma")
        print("2.- Resta")
        print("3.- Multiplicación")
        print("4.- División")
        print("5.- Salir")

        opcion = input("Ingresa el número de la opción que deseas: ")

        if opcion == '1':
            suma()
        elif opcion == '2':
            resta()
        elif opcion == '3':
            multiplicacion()
        elif opcion == '4':
            division()
        elif opcion == '5':
            print("Gracias por usar la calculadora. ¡Adiós mundo!")
            break
        else:
            print("Opción no válida, por favor intenta de nuevo.")