# -*- coding: utf-8 -*-
"""Division.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rw2IaTus0vecyQuiGbwfPbXWsvDOpC9p
"""

def division():
  print("Calculadora de división")
  while True:
    try:
      numerador = float(input("Ingrese el numerador: "))
      denominador = float(input("Ingrese el denominador: "))
      resultado = numerador / denominador
      print(f"El resultado de la división es: {resultado}")
    except ValueError:
      print("Por favor, ingresa un número válido.")
    else:
      continuar = input("¿Quieres hacer otra división? (si/no): ").strip().lower()
      if continuar != 'si':
                menu()
                break