# -*- coding: utf-8 -*-
"""resta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jWkPShZzWVhvMK4APkAhvtfPhKxoKF44
"""

def resta():
  print("Calculadora de resta")
  while True:
    try:
      numero1 = float(input("Ingrese el primer número: "))
      numero2 = float(input("Ingrese el segundo número: "))
      resultado = numero1 - numero2
      print(f"El resultado de la resta es: {resultado}")
    except ValueError:
      print("Por favor, ingresa un número válido.")
    else:
      continuar = input("¿Quieres hacer otra resta? (si/no): ").strip().lower()
      if continuar == 'si':
        continue
      else:
        break