# -*- coding: utf-8 -*-
"""Suma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CMg09vXCHMWboisR8BUCRNXpJ3FWhRru
"""

def suma():
    print("Calculadora de Sumas")
    while True:
        try:
            numero1 = float(input("Ingrese el primer número: "))
            numero2 = float(input("Ingrese el segundo número: "))
            resultado = numero1 + numero2
            print(f"El resultado de la suma es: {resultado}")
        except ValueError:
            print("Por favor, ingrese un número válido.")

        continuar = input("¿Desea realizar otra suma? (si/no): ").lower()
        if continuar == 'si':
            continue
        else:
            break